import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useForm } from 'react-hook-form';

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm();

  const onSubmit = async (data: any) => {
    const response = await fetch('/api/sheet', {
      method: 'POST',
      body: JSON.stringify(data),
      headers: {
        'Content-Type': 'application/json',
      },
    });
    await fetch(`api/contact`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello, form</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input type="text" {...register('name')} />
          <input type="text" {...register('email')} />
          <textarea {...register('message')} />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
